import Login from '@/components/Login'
import React from 'react'

export const metadata = {
    title: "Task Management System | Login",
    description: "Generated by Task Management System",
};
const LoginPage = () => {
    return (
        <Login />
    )
}

export default LoginPage