"use client"
import Login from '@/components/Login'
import { useRouter } from 'next/navigation';
import React, { useEffect } from 'react'
import { useAuth } from '../context/AuthContext';

// export const metadata = {
//     title: "Task Management System | Login",
//     description: "Generated by Task Management System",
// };
const LoginPage = () => {
  const router = useRouter();
  const { isAuthenticated, loading } = useAuth();

  useEffect(() => {
    if (!loading && isAuthenticated) {
      router.replace("/tasks");
    }
  }, [isAuthenticated, loading, router]);

  if (loading) return <p>Loading...</p>;
  if (isAuthenticated) return null;

  return <Login />;
  // return (
  //     <Login />
  // )
}

export default LoginPage