import RegisterPage from '@/components/Register'
import React from 'react'

export const metadata = {
  title: "Task Management System | Signup",
  description: "Generated by Task Management System",
};

const SignUp = () => {
  return (
    <RegisterPage />
  )
}

export default SignUp